import "./globals.css";
import { Inter } from "next/font/google";
import ContextProvider from "@/redux/contextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* wrapping the provider for redux */}
        <ContextProvider>{children}</ContextProvider>
      </body>
    </html>
  );
}
